splash = false

wallpaper {
    monitor = HDMI-A-2
    path = /home/simsin/wallpapers/wallpaper1.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-4
    path = /home/simsin/wallpapers/wallpaper2.jpg
    fit_mode = cover
}
